language: python
python:
    - "2.7"
install:
    - pip install requests junit_xml beaker-client mock
    - pip install pylint flake8
script:
    - flake8 --show-source .
    - python -m unittest discover tests
    - pylint tests
    - pip install .
    - pip uninstall -y skt
