defaults: &defaults
  working_directory: /tmp/skt
  steps:
    - checkout
    - run:
        name: Install skt using pip
        command: pip install .
    - run:
        name: Prepare git
        command: |
          mkdir -p /tmp/skt_test/workdir
          git config --global user.name "SKT"
          git config --global user.email "noreply@redhat.com"
    - run:
        name: Test `skt merge`
        command: |
          skt -vv --state -d workdir --rc sktrc merge \
            --pw https://patchwork.ozlabs.org/patch/895383/ \
            -b git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git \
            --ref v4.16 \
            --fetch-depth 1
        working_directory: /tmp/skt_test
    - run:
        name: Test `skt build`
        command: |
            skt -vv --state -d workdir --rc sktrc build -c config \
                --cfgtype tinyconfig
        working_directory: /tmp/skt_test
    - store_artifacts:
        path: /tmp/skt_test/workdir/*.log
    - store_artifacts:
        path: /tmp/skt_test/workdir/.config
    - store_artifacts:
        path: /tmp/skt_test/*.tar.gz
    - store_artifacts:
        path: /tmp/skt_test/sktrc

version: 2
jobs:
  fedora28:
    docker:
      - image: quay.io/major/fedora28-kernel-builder:latest
    <<: *defaults
  centos7:
    docker:
      - image: quay.io/major/centos-kernel-builder:latest
    <<: *defaults

workflows:
  version: 2
  build_and_test:
    jobs:
      - fedora28
      - centos7
